# Generated by Django 3.1.2 on 2021-02-13 16:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owners', models.ManyToManyField(blank=True, null=True, related_name='contacts', to=settings.AUTH_USER_MODEL)),
                ('relatedUsers', models.ManyToManyField(blank=True, null=True, related_name='relatedUsers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('encrypted', models.BooleanField(default=True)),
                ('relatedContacts', models.ManyToManyField(blank=True, null=True, related_name='contacts', to='contacts.Contact')),
            ],
        ),
    ]
