"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 3.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '66jh5=!211o7(ob%i)dl$7js*!pzzk_3p=@5mv@iz(cf5r%bhl'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.pythonanywhere.com', 'iLikeit.pythonanywhere.com', '*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #...,
    #'corsheaders', # RTG:
    #...,
    'rest_framework', # RTG:
    'rest_framework.authtoken', # RTG:
    'dj_rest_auth', # RTG:
    #...,
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'dj_rest_auth.registration',
    #...,
    'allauth.socialaccount',
    'allauth.socialaccount.providers.facebook', # RTG: example
    'allauth.socialaccount.providers.twitter', # RTG: example
    #...,
    'corsheaders', # RTG:
    'frontend', # RTG:
    #'frontend2', # RTG:
    #'frontend3', # RTG:
    'about', # RTG:
    'selfupdate', # RTG:
    'notes', # RTG:
]

SITE_ID = 1 # RTG: for django.contrib.sites

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware', # RTG
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static')

"""
# RTG: Currently not used
STATICFILES_DIRS = (
    #This lets Django's collectstatic store our bundles
    os.path.join(BASE_DIR, 'assets'),
    os.path.join(BASE_DIR, 'resources'),
)
"""

CORS_ORIGIN_WHITELIST = [
    'http://localhost:3000',
    'http://localhost:8000',
    'http://localhost:8080',
]
# For demo purposes only. Use a white list in the real world.
CORS_ORIGIN_ALLOW_ALL = True


REST_FRAMEWORK = {

    # RTG: Replace API view with JSON - recommenden for production by https://tproger.ru/translations/django-react-webapp/
    #'DEFAULT_RENDERER_CLASSES': (
    #    'rest_framework.renderers.JSONRenderer',
    #),

    # RTG: for auth by https://dj-rest-auth.readthedocs.io/en/latest/installation.html
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        #'rest_framework.authentication.SessionAuthentication', # RTG: why does it cause 403 forbidden?
        'dj_rest_auth.jwt_auth.JWTCookieAuthentication', # RTG: for dj-rest-auth + djangorestframework-simplejwt
    ),

    # RTG: for auth by https://medium.com/quick-code/token-based-authentication-for-django-rest-framework-44586a9a56fb
    # RTG: and https://stackoverflow.com/questions/26906630/django-rest-framework-authentication-credentials-were-not-provided
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAdminUser',
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# RTG: dj-rest-auth config from official demo project
REST_SESSION_LOGIN = True
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# SITE_ID = 1 # see above
ACCOUNT_EMAIL_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'username'
ACCOUNT_EMAIL_VERIFICATION = 'optional'
# RTG: for auth by https://dj-rest-auth.readthedocs.io/en/latest/installation.html
#REST_USE_JWT = True # for JWT only
#JWT_AUTH_COOKIE = 'jwt-auth' # RTG: if JWT_AUTH_COOKIE is not set - on logout i get "Neither cookies or blacklist are enabled, so the token has not been deleted server side. Please make sure the token is deleted client side."
# RTG: drfr with jwt sets to anonymous user, debug it
