# Generated by Django 3.1.2 on 2020-11-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20201025_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='encrypted',
            field=models.BooleanField(default=True),
        ),
    ]
