# Generated by Django 3.1.1 on 2020-09-21 12:11

from django.db import migrations, models
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_processed', models.DateTimeField(default=django.utils.timezone.now)),
                ('team_id', models.CharField(max_length=250)),
                ('team_domain', models.CharField(max_length=250)),
                ('channel_id', models.CharField(max_length=250)),
                ('channel_name', models.CharField(max_length=250)),
                ('user_id', models.CharField(max_length=250)),
                ('user_name', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('trigger_word', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_event_generated', models.DateTimeField()),
                ('date_received', models.DateTimeField(default=django.utils.timezone.now)),
                ('body', jsonfield.fields.JSONField(blank=True, null=True)),
                ('request_meta', jsonfield.fields.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[(1, 'Unprocessed'), (2, 'Processed'), (3, 'Error')], default=1, max_length=250)),
            ],
        ),
    ]
