# Generated by Django 3.1.1 on 2020-09-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='feedback',
            field=models.CharField(max_length=300),
        ),
    ]
