# Generated by Django 3.1.1 on 2020-09-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20200914_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='feedback',
            new_name='contact',
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
